

# ALA SONA WAWA LUPA ONA NANPA IJO ILO OLIN WILE MUTE OKO SEWI LON TENPO JAKI JO NASIN TOKI SUNO UTA WIKE NASA ALI WALO LASO KILI SUPA AWEN LETE AKESI NENA UTALA NIMI SINPIN LAPE SITELEN POKA SAMA MOLI LUKIN JELO PAKALA MA LEN ALE LAWA KIWEN PINI WASO KULUPU PALI JAN OPEN TASO KUTE KALA TELO MONSI LILI KEN TOMO MAMA MIJE PONA SEME TU MELI PIMEJA PIPI NOKA KULE SIN SOWELI SUWI ANTE SIKE KALAMA LINJA KASI SIJELO MUN PANA TAWA LOJE TAN KEPEKEN KAMA SELO MI POKI SELI IKE PILIN WAN LUKA MANI ANPA SULI MUSI WEKA INSA LIPU MOKU KIN SINA NI UNPA PALISA LI LA O ANU EN E


words_line = "ALA SONA WAWA LUPA ONA NANPA IJO ILO OLIN WILE MUTE OKO SEWI LON TENPO JAKI JO NASIN TOKI SUNO UTA WIKE NASA ALI WALO LASO KILI SUPA AWEN LETE AKESI NENA UTALA NIMI SINPIN LAPE SITELEN POKA SAMA MOLI LUKIN JELO PAKALA MA LEN ALE LAWA KIWEN PINI WASO KULUPU PALI JAN OPEN TASO KUTE KALA TELO MONSI LILI KEN TOMO MAMA MIJE PONA SEME TU MELI PIMEJA PIPI NOKA KULE SIN SOWELI SUWI ANTE SIKE KALAMA LINJA KASI SIJELO MUN PANA TAWA LOJE TAN KEPEKEN KAMA SELO MI POKI SELI IKE PILIN WAN LUKA MANI ANPA SULI MUSI WEKA INSA LIPU MOKU KIN SINA NI UNPA PALISA LI LA O ANU EN E"

words = words_line.split(" ")
words.append("ENDMARK")

for word in words:

    print("{:<10}".format(word.lower()) + '{printf("%d\\t",' + word + ");}")

