

if __name__ == "__main__":

    string = "ILO PALISA LIPU OLIN ANTE WASO UNPA SIJELO TENPO LILI LAPE PINI KIN IJO MUN PALI SELI LINJA PAKALA KULE WILE LUPA UTA ALI KULUPU ONA SIN UTALA MONSI LEN SITELEN MI KASI MUSI AWEN JO NASA NENA WAN PIMEJA KILI SELO SONA OKO TU KALAMA SIKE SINA INSA KALA JELO PILIN PONA NIMI PANA TASO KEN JAKI MELI LOJE SINPIN PIPI MUTE WIKE TOKI MANI JAN TAWA KEPEKEN LUKIN TAN AKESI KAMA NOKA MOKU LAWA TELO LASO WEKA IKE LETE MOLI LON SUPA NASIN TOMO KUTE SUNO POKI SEME MA SOWELI NI MAMA MIJE WALO NANPA ALA KIWEN OPEN POKA LUKA SAMA SULI ALE SEWI ANPA WAWA SUWI LI LA O ANU EN E"

    words = string.split(" ")

    for w in words:
        print("{:<10}".format(w.lower()) + " {yylval = strdup(yytext); " + "return {};".format(w) + "}")

